### ISSUE TITLE
doautocmd when done pulsing

### ISSUE THREAD

**Issue by jebaum** [inside/vim-search-pulse#10]
I found that I liked having `cursorcolumn` set while the actual pulse is happening to really direct my eyes to the exact location of the match, and then having `cursorcolumn` be automatically unset after the pulse is over. To achieve this I added the line

`doautocmd <nomodeline> User PostPulse`

to the end of the `search_pulse#Pulse()` function, and adjusted my maps and added an autocmd to handle it. This seems potentially useful for other things as well, would you be interested in a PR for it?

**Comment by inside** [comment]
I would be very interested in this. I think I'd like this behavior too in my everyday code editing.

Could you also provide an example in the readme and/or the docs to demonstrate this autocommand usage?

Since we have a `PostPulse` does a `PrePulse` make sense to you? I imagine we can use it to do `set cursorcolumn` or other things.

**Comment by jebaum** [comment]
Yeah will do. PrePulse could be nice as well, I'll throw that in. I suppose these should also be triggered before and after the return path in the `if` block of `PulseFirst()`. I'll send a PR soon

**Comment by inside** [comment]
Cool, take your time. Since `PulseFirst()` calls `Pulse()`, I would trigger these in the `Pulse()` function, maybe before line 74 and after line 78.

**Comment by jebaum** [comment]
yeah somehow I overlooked that.

**Comment by inside** [comment]
:-)
