### ISSUE TITLE
When set number, <Plug>Pulse will flash at the background of fisrt digit line number, right next to the next line of the search pattern  

### ISSUE THREAD

**Issue by zuxfoucault** [inside/vim-search-pulse#6]
The issue is:
When `set number`, `<Plug>Pulse` will flash at the background of the first digit of line number, right next to the line of the search pattern.

I use MacVim, and
let g:vim_search_pulse_mode = 'pattern'
let g:vim_search_pulse_disable_auto_mappings = 1

**Comment by inside** [comment]
Hi zuxfoucault,

What is your vim version? I remember having this unwanted blinking, but now I can't reproduce it with my current vim:

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  5 2015 09:56:42)
Included patches: 1-621
```

**Comment by zuxfoucault** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 25 2014 12:31:24)
Compiled by Homebrew

**Comment by inside** [comment]
I remember more clearly now, the blinking I noticed was when using terminal vim and `let g:vim_search_pulse_mode = 'cursor_line'`. It occured at the bottom left, on the command line, not in the gutter, where the line numbers are.

The bug you have is MacVim related. I just updated the readme with some infos:
https://github.com/inside/vim-search-pulse#macvim

If you have some time, you can try to install the HEAD version of MacVim to see if it was fixed. Otherwise, I guess will have to wait for a fix.

Best
